import type { WorkTask } from "./work-board-types";

export const mockWorkTasks: WorkTask[] = [
  {
    id: "task-content-draft",
    title: "블로그 포스트 「6월 루틴 정리」 초안 작성",
    assigneeId: "content-planner",
    department: "콘텐츠팀",
    status: "진행 중",
    priority: "보통",
    progress: 68,
    started: "13:50",
    model: "Claude Opus 4.6",
    cost: "$0.82",
    purpose: "BG Company 운영 기록을 외부 콘텐츠로 정리해 브랜드 신뢰도를 높입니다.",
    currentStep: "본문 초안 구조 다듬기",
    steps: [
      { label: "주제 수집", done: true },
      { label: "초안 작성", done: true },
      { label: "제목 A/B안 생성", done: false },
      { label: "대표 승인 요청", done: false },
    ],
    approvalRequired: false,
    output: "초안 v2 · 1,240자",
    nextAction: "제목 A/B안 생성",
  },
  {
    id: "task-thumbnail-approval",
    title: "유튜브 썸네일 3종 검수 요청",
    assigneeId: "marketing-manager",
    department: "콘텐츠팀",
    status: "승인 대기",
    priority: "높음",
    progress: 100,
    started: "13:35",
    model: "Claude Opus 4.6",
    cost: "$0.61",
    purpose: "다음 콘텐츠 업로드 전 썸네일 후보를 검수하고 최종안을 확정합니다.",
    currentStep: "대표 승인 대기",
    steps: [
      { label: "후보 이미지 정리", done: true },
      { label: "카피 문구 정리", done: true },
      { label: "승인 요청", done: true },
      { label: "최종 반영", done: false },
    ],
    approvalRequired: true,
    output: "썸네일 3종",
    nextAction: "대표 승인 필요",
  },
  {
    id: "task-dev-pipeline",
    title: "배포 파이프라인 빌드 오류 수정",
    assigneeId: "developer",
    department: "개발팀",
    status: "오류",
    priority: "높음",
    progress: 30,
    started: "14:18",
    model: "GPT-5.1 Codex",
    cost: "$0.46",
    purpose: "Phase 1-A 웹 앱의 배포 가능 상태를 회복합니다.",
    currentStep: "빌드 실패 로그 원인 분석",
    steps: [
      { label: "오류 감지", done: true },
      { label: "로그 분석", done: true },
      { label: "핫픽스 작성", done: false },
      { label: "재빌드 검증", done: false },
    ],
    approvalRequired: false,
    error: "빌드 단계 exit code 1 · 자동 재시도 1회 실패",
    output: "에러 로그 분석",
    nextAction: "핫픽스 PR 생성",
  },
  {
    id: "task-cost-review",
    title: "6월 운영비 정산 및 현금흐름 검토",
    assigneeId: "finance-manager",
    department: "재정팀",
    status: "진행 중",
    priority: "보통",
    progress: 54,
    started: "13:42",
    model: "GPT-5.1",
    cost: "$0.58",
    purpose: "이번 달 AI 비용과 운영비를 정리해 다음 집행 판단 근거를 만듭니다.",
    currentStep: "비용 이상치 검토",
    steps: [
      { label: "비용 데이터 수집", done: true },
      { label: "현금흐름 요약", done: true },
      { label: "이상치 검토", done: false },
      { label: "보고서 초안 작성", done: false },
    ],
    approvalRequired: false,
    output: "주간 비용 요약",
    nextAction: "비용 이상치 검토",
  },
  {
    id: "task-stock-watch",
    title: "관심 종목 장중 변동 모니터링",
    assigneeId: "stock-monitor",
    department: "주식팀",
    status: "진행 중",
    priority: "보통",
    progress: 42,
    started: "13:28",
    model: "Claude Sonnet 4.6",
    cost: "$0.37",
    purpose: "시장 변동성을 추적하고 대표 보고가 필요한 신호를 선별합니다.",
    currentStep: "변동성 이벤트 조사",
    steps: [
      { label: "가격 변동 감지", done: true },
      { label: "뉴스/공시 확인", done: false },
      { label: "리스크 요약", done: false },
    ],
    approvalRequired: false,
    output: "변동성 감지 리포트",
    nextAction: "대표 보고 준비",
  },
  {
    id: "task-qa-check",
    title: "Phase 1-A 품질 기준 검토",
    assigneeId: "qa-auditor",
    department: "지식·감사",
    status: "진행 중",
    priority: "보통",
    progress: 76,
    started: "13:20",
    model: "Claude Opus 4.6",
    cost: "$0.69",
    purpose: "가상 오피스 UI와 동선 기능이 Phase 1-A 기준을 만족하는지 점검합니다.",
    currentStep: "디자인 오차 보고",
    steps: [
      { label: "검증 항목 정리", done: true },
      { label: "오피스 배치 점검", done: true },
      { label: "동선/선택 연동 확인", done: true },
      { label: "최종 보고", done: false },
    ],
    approvalRequired: false,
    output: "QA 체크리스트 v3",
    nextAction: "디자인 오차 보고",
  },
];
