import type { ApprovalRequest } from "./approval-types";

export const mockApprovals: ApprovalRequest[] = [
  {
    id: "approval-thumbnail",
    title: "유튜브 썸네일 3종 최종안 승인",
    employeeId: "marketing-manager",
    type: "콘텐츠",
    risk: "보통",
    estimatedCost: "$0.61",
    status: "승인 대기",
    requestedAt: "14:21",
    relatedTaskId: "task-thumbnail-approval",
    reason: "다음 콘텐츠 업로드 전 대표 최종 검수 필요",
    plannedAction: "승인된 썸네일을 콘텐츠 캘린더에 등록",
    expectedResult: "오늘 18:00 업로드 준비 완료",
    output: "썸네일 후보 A/B/C",
  },
  {
    id: "approval-budget",
    title: "AI 모델 사용량 증액 승인",
    employeeId: "finance-manager",
    type: "비용",
    risk: "낮음",
    estimatedCost: "$12.40",
    status: "승인 대기",
    requestedAt: "14:12",
    relatedTaskId: "task-cost-review",
    reason: "콘텐츠 회의 이후 결과물 생성량 증가 예상",
    plannedAction: "오늘 잔여 예산 한도 내 모델 호출량 상향",
    expectedResult: "업무 지연 없이 콘텐츠 초안 생성 지속",
    output: "비용 영향 추정표",
  },
  {
    id: "approval-hotfix",
    title: "배포 파이프라인 핫픽스 적용 승인",
    employeeId: "developer",
    type: "오류",
    risk: "높음",
    estimatedCost: "$0.46",
    status: "보류",
    requestedAt: "14:24",
    relatedTaskId: "task-dev-pipeline",
    reason: "빌드 오류 원인 패치 후 재배포 필요",
    plannedAction: "핫픽스 브랜치 검증 후 배포 파이프라인 재실행",
    expectedResult: "프로덕션 빌드 정상화",
    output: "에러 로그 분석",
  },
];
